### ISSUE TITLE
Кто ты, воин?

### ISSUE THREAD

**Issue by DPrison** [furryhater2008/DHack-Unturned#2]
Кто ты, воин? Я даже не допёр, шадоу йорик ты или кто там я хз

**Comment by furryhater2008** [comment]
я твой папа

**Comment by DPrison** [comment]
Можешь ли ты там вычислить меня по настоящему, а не говорить что узбеки приедут? Только такими тактиками и можешь, вливаешся в доверие, а потом сурсы сливаешь, сурсы читов тех людей, которые меньше всего виновны, тоесть практически не виновны. А сам на ничего более не способен, может ддосить по айпише, всё. Ну слишком всё тут ясно, кто нас настолько сильно ненавидит, что наш исходник сливает, хотя даже сурсы туркишов на гите нету? Ладно уж, продажи чита этого не сильно подбъют, ну и сиди, дальше морально изнашивай нормальных людей, мне уже до кучи.

**Comment by furryhater2008** [comment]
мужик чекай скоро к тебе спортики подьедут
